function mainShow(n) {
  stroke(100);
  strokeWeight(10);
  noFill();
  var d = map(mouseY, 0, height, 100, sin(60) * 25.882 * 4 + 25.882 * 2);
  var w = d * sin(60);
  var h = d * sin(30);

  push();
  translate(width / 2, height / 2);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2, height / 2 - d);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2, height / 2 + d);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2 + w, height / 2 + h);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2 - w, height / 2 + h);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2 - w, height / 2 - h);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2 + w, height / 2 - h);
  rotate(15);
  polygon(0, 0, n);
  pop();

  push();
  translate(width / 2 + 2 * w, height / 2 - 2 * h);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2 - 2 * w, height / 2 - 2 * h);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2 + 2 * w, height / 2 + 2 * h);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2 - 2 * w, height / 2 + 2 * h);
  rotate(15);
  polygon(0, 0, n);
  pop();

  push();
  translate(width / 2 - w, height / 2 + 3 * h);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2 + w, height / 2 + 3 * h);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2 - w, height / 2 - 3 * h);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2 + w, height / 2 - 3 * h);
  rotate(15);
  polygon(0, 0, n);
  pop();

  push();
  translate(width / 2 + 2 * w, height / 2);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2 - 2 * w, height / 2);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2, height / 2 - 4 * h);
  rotate(15);
  polygon(0, 0, n);
  pop();
  push();
  translate(width / 2, height / 2 + 4 * h);
  rotate(15);
  polygon(0, 0, n);
  pop();
}
